// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4wu8SqaGVjBvXIH5WVauIQtUUQVJUh7g',
    appId: '1:168145515138:web:9c147a113750b52567ba9b',
    messagingSenderId: '168145515138',
    projectId: 'budjar-8d2e9',
    authDomain: 'budjar-8d2e9.firebaseapp.com',
    storageBucket: 'budjar-8d2e9.firebasestorage.app',
    measurementId: 'G-QHC5FE34BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvAQX2TI6qz4BIdhhzCWWJv2xVF1qSlPU',
    appId: '1:168145515138:android:cd1045ca6cad299867ba9b',
    messagingSenderId: '168145515138',
    projectId: 'budjar-8d2e9',
    storageBucket: 'budjar-8d2e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5TcJ4hUorH8irBEp3-EeCNKjLv4MjpZA',
    appId: '1:168145515138:ios:6fc4511e788e035c67ba9b',
    messagingSenderId: '168145515138',
    projectId: 'budjar-8d2e9',
    storageBucket: 'budjar-8d2e9.firebasestorage.app',
    iosClientId:
        '168145515138-2a4d82di131oh1236lde0pijdvudjkfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.budjar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5TcJ4hUorH8irBEp3-EeCNKjLv4MjpZA',
    appId: '1:168145515138:ios:6fc4511e788e035c67ba9b',
    messagingSenderId: '168145515138',
    projectId: 'budjar-8d2e9',
    storageBucket: 'budjar-8d2e9.firebasestorage.app',
    iosClientId:
        '168145515138-2a4d82di131oh1236lde0pijdvudjkfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.budjar',
  );
}
